name = "auto-reaction-bot"
main = "src/index.js"
compatibility_date = "2024-02-08"

[vars]
BOT_TOKEN = "12345678:PAST-YOUR-BOT-TOKEN-HERE"
BOT_USERNAME = "Auto_ReactionBOT"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "2"
RESTRICTED_CHATS = "1234,5678"